// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smartWasteManagementService.proto

package com.waste.service;

public interface GetBinLocatorResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smart_power.GetBinLocatorResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string nearestRecyclingBin = 1;</code>
   */
  java.lang.String getNearestRecyclingBin();
  /**
   * <code>string nearestRecyclingBin = 1;</code>
   */
  com.google.protobuf.ByteString
      getNearestRecyclingBinBytes();
}
