// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smartWasteManagementService.proto

package com.waste.service;

public interface GetBinLocatorRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smart_power.GetBinLocatorRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string currentLocation = 1;</code>
   */
  java.lang.String getCurrentLocation();
  /**
   * <code>string currentLocation = 1;</code>
   */
  com.google.protobuf.ByteString
      getCurrentLocationBytes();
}
