// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smartWasteManagementService.proto

package com.waste.service;

public interface GetCustomizedRouteResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smart_power.GetCustomizedRouteResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string optimizedRoute = 1;</code>
   */
  java.lang.String getOptimizedRoute();
  /**
   * <code>string optimizedRoute = 1;</code>
   */
  com.google.protobuf.ByteString
      getOptimizedRouteBytes();

  /**
   * <code>int32 binLevel1 = 2;</code>
   */
  int getBinLevel1();

  /**
   * <code>int32 binLevel2 = 3;</code>
   */
  int getBinLevel2();
}
