// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smartWasteManagementService.proto

package com.waste.service;

public interface GetCustomizedRouteRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smart_power.GetCustomizedRouteRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 binLevel1 = 1;</code>
   */
  int getBinLevel1();
}
