// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smartWasteManagementService.proto

package com.waste.service;

public final class SmartWasteManagementServiceImpl {
  private SmartWasteManagementServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smart_power_GetCustomizedRouteRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smart_power_GetCustomizedRouteRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smart_power_GetCustomizedRouteResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smart_power_GetCustomizedRouteResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smart_power_GetBinLocatorRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smart_power_GetBinLocatorRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smart_power_GetBinLocatorResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smart_power_GetBinLocatorResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n!smartWasteManagementService.proto\022\013sma" +
      "rt_power\".\n\031GetCustomizedRouteRequest\022\021\n" +
      "\tbinLevel1\030\001 \001(\005\"Z\n\032GetCustomizedRouteRe" +
      "sponse\022\026\n\016optimizedRoute\030\001 \001(\t\022\021\n\tbinLev" +
      "el1\030\002 \001(\005\022\021\n\tbinLevel2\030\003 \001(\005\"/\n\024GetBinLo" +
      "catorRequest\022\027\n\017currentLocation\030\001 \001(\t\"4\n" +
      "\025GetBinLocatorResponse\022\033\n\023nearestRecycli" +
      "ngBin\030\001 \001(\t2\342\001\n\033SmartWasteManagementServ" +
      "ice\022i\n\022GetCustomizedRoute\022&.smart_power." +
      "GetCustomizedRouteRequest\032\'.smart_power." +
      "GetCustomizedRouteResponse\"\000(\001\022X\n\rGetBin" +
      "Locator\022!.smart_power.GetBinLocatorReque" +
      "st\032\".smart_power.GetBinLocatorResponse\"\000" +
      "B6\n\021com.waste.serviceB\037SmartWasteManagem" +
      "entServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_smart_power_GetCustomizedRouteRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_smart_power_GetCustomizedRouteRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smart_power_GetCustomizedRouteRequest_descriptor,
        new java.lang.String[] { "BinLevel1", });
    internal_static_smart_power_GetCustomizedRouteResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_smart_power_GetCustomizedRouteResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smart_power_GetCustomizedRouteResponse_descriptor,
        new java.lang.String[] { "OptimizedRoute", "BinLevel1", "BinLevel2", });
    internal_static_smart_power_GetBinLocatorRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_smart_power_GetBinLocatorRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smart_power_GetBinLocatorRequest_descriptor,
        new java.lang.String[] { "CurrentLocation", });
    internal_static_smart_power_GetBinLocatorResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_smart_power_GetBinLocatorResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smart_power_GetBinLocatorResponse_descriptor,
        new java.lang.String[] { "NearestRecyclingBin", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
