// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smartPowerService.proto

package com.power.service;

public interface GetEnergyConsumptionRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smart_power.GetEnergyConsumptionRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 deviceId = 1;</code>
   */
  int getDeviceId();
}
