// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smartPowerService.proto

package com.power.service;

/**
 * Protobuf type {@code smart_power.GetEnergyConsumptionResponse}
 */
public  final class GetEnergyConsumptionResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:smart_power.GetEnergyConsumptionResponse)
    GetEnergyConsumptionResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetEnergyConsumptionResponse.newBuilder() to construct.
  private GetEnergyConsumptionResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetEnergyConsumptionResponse() {
    energyConsumption_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GetEnergyConsumptionResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            energyConsumption_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.power.service.SmartPowerServiceImpl.internal_static_smart_power_GetEnergyConsumptionResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.power.service.SmartPowerServiceImpl.internal_static_smart_power_GetEnergyConsumptionResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.power.service.GetEnergyConsumptionResponse.class, com.power.service.GetEnergyConsumptionResponse.Builder.class);
  }

  public static final int ENERGYCONSUMPTION_FIELD_NUMBER = 1;
  private int energyConsumption_;
  /**
   * <code>int32 energyConsumption = 1;</code>
   */
  public int getEnergyConsumption() {
    return energyConsumption_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (energyConsumption_ != 0) {
      output.writeInt32(1, energyConsumption_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (energyConsumption_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, energyConsumption_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.power.service.GetEnergyConsumptionResponse)) {
      return super.equals(obj);
    }
    com.power.service.GetEnergyConsumptionResponse other = (com.power.service.GetEnergyConsumptionResponse) obj;

    boolean result = true;
    result = result && (getEnergyConsumption()
        == other.getEnergyConsumption());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ENERGYCONSUMPTION_FIELD_NUMBER;
    hash = (53 * hash) + getEnergyConsumption();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.power.service.GetEnergyConsumptionResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.power.service.GetEnergyConsumptionResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.power.service.GetEnergyConsumptionResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.power.service.GetEnergyConsumptionResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.power.service.GetEnergyConsumptionResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.power.service.GetEnergyConsumptionResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.power.service.GetEnergyConsumptionResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.power.service.GetEnergyConsumptionResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.power.service.GetEnergyConsumptionResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.power.service.GetEnergyConsumptionResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.power.service.GetEnergyConsumptionResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.power.service.GetEnergyConsumptionResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.power.service.GetEnergyConsumptionResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code smart_power.GetEnergyConsumptionResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:smart_power.GetEnergyConsumptionResponse)
      com.power.service.GetEnergyConsumptionResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.power.service.SmartPowerServiceImpl.internal_static_smart_power_GetEnergyConsumptionResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.power.service.SmartPowerServiceImpl.internal_static_smart_power_GetEnergyConsumptionResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.power.service.GetEnergyConsumptionResponse.class, com.power.service.GetEnergyConsumptionResponse.Builder.class);
    }

    // Construct using com.power.service.GetEnergyConsumptionResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      energyConsumption_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.power.service.SmartPowerServiceImpl.internal_static_smart_power_GetEnergyConsumptionResponse_descriptor;
    }

    @java.lang.Override
    public com.power.service.GetEnergyConsumptionResponse getDefaultInstanceForType() {
      return com.power.service.GetEnergyConsumptionResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.power.service.GetEnergyConsumptionResponse build() {
      com.power.service.GetEnergyConsumptionResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.power.service.GetEnergyConsumptionResponse buildPartial() {
      com.power.service.GetEnergyConsumptionResponse result = new com.power.service.GetEnergyConsumptionResponse(this);
      result.energyConsumption_ = energyConsumption_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.power.service.GetEnergyConsumptionResponse) {
        return mergeFrom((com.power.service.GetEnergyConsumptionResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.power.service.GetEnergyConsumptionResponse other) {
      if (other == com.power.service.GetEnergyConsumptionResponse.getDefaultInstance()) return this;
      if (other.getEnergyConsumption() != 0) {
        setEnergyConsumption(other.getEnergyConsumption());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.power.service.GetEnergyConsumptionResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.power.service.GetEnergyConsumptionResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int energyConsumption_ ;
    /**
     * <code>int32 energyConsumption = 1;</code>
     */
    public int getEnergyConsumption() {
      return energyConsumption_;
    }
    /**
     * <code>int32 energyConsumption = 1;</code>
     */
    public Builder setEnergyConsumption(int value) {
      
      energyConsumption_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 energyConsumption = 1;</code>
     */
    public Builder clearEnergyConsumption() {
      
      energyConsumption_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:smart_power.GetEnergyConsumptionResponse)
  }

  // @@protoc_insertion_point(class_scope:smart_power.GetEnergyConsumptionResponse)
  private static final com.power.service.GetEnergyConsumptionResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.power.service.GetEnergyConsumptionResponse();
  }

  public static com.power.service.GetEnergyConsumptionResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetEnergyConsumptionResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetEnergyConsumptionResponse>() {
    @java.lang.Override
    public GetEnergyConsumptionResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GetEnergyConsumptionResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetEnergyConsumptionResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetEnergyConsumptionResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.power.service.GetEnergyConsumptionResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

