// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smartPowerService.proto

package com.power.service;

public interface GetEnergyConsumptionResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smart_power.GetEnergyConsumptionResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 energyConsumption = 1;</code>
   */
  int getEnergyConsumption();
}
