// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smartPowerService.proto

package com.power.service;

public interface SetMaxEnergyLimitRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smart_power.SetMaxEnergyLimitRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 maxEnergyLimit = 1;</code>
   */
  int getMaxEnergyLimit();
}
