// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smartPowerService.proto

package com.power.service;

public interface SetMaxEnergyLimitResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smart_power.SetMaxEnergyLimitResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>int32 currentMaxEnergyLimit = 2;</code>
   */
  int getCurrentMaxEnergyLimit();
}
