// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smartPowerService.proto

package com.power.service;

public final class SmartPowerServiceImpl {
  private SmartPowerServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smart_power_GetEnergyConsumptionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smart_power_GetEnergyConsumptionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smart_power_GetEnergyConsumptionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smart_power_GetEnergyConsumptionResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smart_power_SetMaxEnergyLimitRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smart_power_SetMaxEnergyLimitRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smart_power_SetMaxEnergyLimitResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smart_power_SetMaxEnergyLimitResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smart_power_GetTotalEnergyConsumptionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smart_power_GetTotalEnergyConsumptionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smart_power_GetTotalEnergyConsumptionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smart_power_GetTotalEnergyConsumptionResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027smartPowerService.proto\022\013smart_power\"/" +
      "\n\033GetEnergyConsumptionRequest\022\020\n\010deviceI" +
      "d\030\001 \001(\005\"9\n\034GetEnergyConsumptionResponse\022" +
      "\031\n\021energyConsumption\030\001 \001(\005\"2\n\030SetMaxEner" +
      "gyLimitRequest\022\026\n\016maxEnergyLimit\030\001 \001(\005\"K" +
      "\n\031SetMaxEnergyLimitResponse\022\017\n\007message\030\001" +
      " \001(\t\022\035\n\025currentMaxEnergyLimit\030\002 \001(\005\"4\n G" +
      "etTotalEnergyConsumptionRequest\022\020\n\010devic" +
      "eId\030\001 \001(\005\"4\n!GetTotalEnergyConsumptionRe" +
      "sponse\022\017\n\007message\030\001 \001(\t2\352\002\n\021SmartPowerSe" +
      "rvice\022m\n\024getEnergyConsumption\022(.smart_po" +
      "wer.GetEnergyConsumptionRequest\032).smart_" +
      "power.GetEnergyConsumptionResponse\"\000\022f\n\021" +
      "setMaxEnergyLimit\022%.smart_power.SetMaxEn" +
      "ergyLimitRequest\032&.smart_power.SetMaxEne" +
      "rgyLimitResponse\"\0000\001\022~\n\031GetTotalEnergyCo" +
      "nsumption\022-.smart_power.GetTotalEnergyCo" +
      "nsumptionRequest\032..smart_power.GetTotalE" +
      "nergyConsumptionResponse\"\000(\001B,\n\021com.powe" +
      "r.serviceB\025SmartPowerServiceImplP\001b\006prot" +
      "o3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_smart_power_GetEnergyConsumptionRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_smart_power_GetEnergyConsumptionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smart_power_GetEnergyConsumptionRequest_descriptor,
        new java.lang.String[] { "DeviceId", });
    internal_static_smart_power_GetEnergyConsumptionResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_smart_power_GetEnergyConsumptionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smart_power_GetEnergyConsumptionResponse_descriptor,
        new java.lang.String[] { "EnergyConsumption", });
    internal_static_smart_power_SetMaxEnergyLimitRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_smart_power_SetMaxEnergyLimitRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smart_power_SetMaxEnergyLimitRequest_descriptor,
        new java.lang.String[] { "MaxEnergyLimit", });
    internal_static_smart_power_SetMaxEnergyLimitResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_smart_power_SetMaxEnergyLimitResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smart_power_SetMaxEnergyLimitResponse_descriptor,
        new java.lang.String[] { "Message", "CurrentMaxEnergyLimit", });
    internal_static_smart_power_GetTotalEnergyConsumptionRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_smart_power_GetTotalEnergyConsumptionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smart_power_GetTotalEnergyConsumptionRequest_descriptor,
        new java.lang.String[] { "DeviceId", });
    internal_static_smart_power_GetTotalEnergyConsumptionResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_smart_power_GetTotalEnergyConsumptionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smart_power_GetTotalEnergyConsumptionResponse_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
