// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smartPublicLightingService.proto

package com.lighting.service;

public interface AdjustLightingResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smart_power.AdjustLightingResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string brightness = 1;</code>
   */
  java.lang.String getBrightness();
  /**
   * <code>string brightness = 1;</code>
   */
  com.google.protobuf.ByteString
      getBrightnessBytes();
}
