// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smartPublicLightingService.proto

package com.lighting.service;

public interface AdjustLightingRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smart_power.AdjustLightingRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string lightLevel = 1;</code>
   */
  java.lang.String getLightLevel();
  /**
   * <code>string lightLevel = 1;</code>
   */
  com.google.protobuf.ByteString
      getLightLevelBytes();

  /**
   * <code>int32 time = 2;</code>
   */
  int getTime();

  /**
   * <code>string location = 3;</code>
   */
  java.lang.String getLocation();
  /**
   * <code>string location = 3;</code>
   */
  com.google.protobuf.ByteString
      getLocationBytes();
}
