// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smartPublicLightingService.proto

package com.lighting.service;

public final class SmartPublicLightingServiceImpl {
  private SmartPublicLightingServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smart_power_AdjustLightingRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smart_power_AdjustLightingRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smart_power_AdjustLightingResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smart_power_AdjustLightingResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smart_power_TurnOnAndOffLightingRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smart_power_TurnOnAndOffLightingRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smart_power_TurnOnAndOffLightingResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smart_power_TurnOnAndOffLightingResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n smartPublicLightingService.proto\022\013smar" +
      "t_power\"K\n\025AdjustLightingRequest\022\022\n\nligh" +
      "tLevel\030\001 \001(\t\022\014\n\004time\030\002 \001(\005\022\020\n\010location\030\003" +
      " \001(\t\",\n\026AdjustLightingResponse\022\022\n\nbright" +
      "ness\030\001 \001(\t\">\n\033TurnOnAndOffLightingReques" +
      "t\022\020\n\010location\030\001 \001(\t\022\r\n\005is_on\030\002 \001(\010\"D\n\034Tu" +
      "rnOnAndOffLightingResponse\022\017\n\007message\030\001 " +
      "\001(\t\022\023\n\013status_code\030\002 \001(\0052\350\001\n\032SmartPublic" +
      "LightingService\022[\n\016AdjustLighting\022\".smar" +
      "t_power.AdjustLightingRequest\032#.smart_po" +
      "wer.AdjustLightingResponse\"\000\022m\n\024TurnOnAn" +
      "dOffLighting\022(.smart_power.TurnOnAndOffL" +
      "ightingRequest\032).smart_power.TurnOnAndOf" +
      "fLightingResponse\"\000B8\n\024com.lighting.serv" +
      "iceB\036SmartPublicLightingServiceImplP\001b\006p" +
      "roto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_smart_power_AdjustLightingRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_smart_power_AdjustLightingRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smart_power_AdjustLightingRequest_descriptor,
        new java.lang.String[] { "LightLevel", "Time", "Location", });
    internal_static_smart_power_AdjustLightingResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_smart_power_AdjustLightingResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smart_power_AdjustLightingResponse_descriptor,
        new java.lang.String[] { "Brightness", });
    internal_static_smart_power_TurnOnAndOffLightingRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_smart_power_TurnOnAndOffLightingRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smart_power_TurnOnAndOffLightingRequest_descriptor,
        new java.lang.String[] { "Location", "IsOn", });
    internal_static_smart_power_TurnOnAndOffLightingResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_smart_power_TurnOnAndOffLightingResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smart_power_TurnOnAndOffLightingResponse_descriptor,
        new java.lang.String[] { "Message", "StatusCode", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
