// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smartPublicLightingService.proto

package com.lighting.service;

public interface TurnOnAndOffLightingRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smart_power.TurnOnAndOffLightingRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string location = 1;</code>
   */
  java.lang.String getLocation();
  /**
   * <code>string location = 1;</code>
   */
  com.google.protobuf.ByteString
      getLocationBytes();

  /**
   * <code>bool is_on = 2;</code>
   */
  boolean getIsOn();
}
