// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smartPublicLightingService.proto

package com.lighting.service;

public interface TurnOnAndOffLightingResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smart_power.TurnOnAndOffLightingResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>int32 status_code = 2;</code>
   */
  int getStatusCode();
}
